name: movie_app
description: A basic movie info app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  io: ^1.0.4
  dartpy: ^0.0.1+4
  dartdoc: ^6.2.2
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  web_socket_channel: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
